USE GD1C2022
GO

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'BI_TIEMPO')
CREATE TABLE LOCRO.BI_TIEMPO(
TIEMPO_ID INT IDENTITY PRIMARY KEY,
TIEMPO_ANIO INT not null,
TIEMPO_CUATRIMESTRE INT null,
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'BI_ESCUDERIA')
CREATE TABLE LOCRO.BI_ESCUDERIA(
ESCUDERIA_ID INT PRIMARY KEY,
ESCUDERIA_NOMBRE VARCHAR(255)
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'BI_CIRCUITO')
CREATE TABLE LOCRO.BI_CIRCUITO(
CIRCUITO_ID INT PRIMARY KEY,
CIRCUITO_NOMBRE VARCHAR(255)
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'BI_CARRERA')
CREATE TABLE LOCRO.BI_CARRERA(
CARRERA_ID INT PRIMARY KEY,
CARRERA_CIRCUITO INT FOREIGN KEY REFERENCES LOCRO.BI_CIRCUITO(CIRCUITO_ID),
CARRERA_FECHA DATE
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'BI_AUTO')
CREATE TABLE LOCRO.BI_AUTO(
AUTO_ID INT PRIMARY KEY,
AUTO_ESCUDERIA INT FOREIGN KEY REFERENCES LOCRO.BI_ESCUDERIA(ESCUDERIA_ID)
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'BI_PARADA_BOX')
CREATE TABLE LOCRO.BI_PARADA_BOX(
PARADA_ID INT PRIMARY KEY,
PARADA_AUTO INT FOREIGN KEY REFERENCES LOCRO.BI_AUTO(AUTO_ID),
PARADA_CARRERA INT FOREIGN KEY REFERENCES LOCRO.BI_CARRERA(CARRERA_ID),
PARADA_TIEMPO decimal(18,2)
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'BI_PARADAS_ESCUDERIAS_CIRCUITO')
CREATE TABLE LOCRO.BI_PARADAS_ESCUDERIAS_CIRCUITO(
CIRCUITO_ID INT NOT NULL,
ESCUDERIA_ID INT NOT NULL,
PARADA_ID INT NOT NULL,
ANIO INT NOT NULL,
CUATRIMESTRE INT NOT NULL,
PARADA_TIEMPO decimal(18,2),
ESCUDERIA_NOMBRE varchar(255),
CIRCUITO_NOMBRE varchar(255),
PRIMARY KEY(CIRCUITO_ID, ESCUDERIA_ID, PARADA_ID)
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'BI_TIPO_SECTOR')
CREATE TABLE LOCRO.BI_TIPO_SECTOR(
TIPO_SECTOR_ID INT PRIMARY KEY,
TIPO_SECTOR_DETALLE varchar(255)
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'BI_SECTOR')
CREATE TABLE LOCRO.BI_SECTOR(
SECTOR_ID INT PRIMARY KEY,
SECTOR_TIPO INT FOREIGN KEY REFERENCES LOCRO.BI_TIPO_SECTOR(TIPO_SECTOR_ID)
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'BI_TIPO_INCIDENTE')
CREATE TABLE LOCRO.BI_TIPO_INCIDENTE(
TIPO_INCIDENTE_ID INT PRIMARY KEY,
TIPO_INCIDENTE_DETALLE varchar(255)
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'BI_INCIDENTE_CIRCUITO')
CREATE TABLE LOCRO.BI_INCIDENTE_CIRCUITO(
INCIDENTE_ID INT NOT NULL,
INCIDENTE_AUTO INT NOT NULL FOREIGN KEY REFERENCES LOCRO.BI_AUTO(AUTO_ID),
INCIDENTE_CIRCUITO INT NOT NULL FOREIGN KEY REFERENCES LOCRO.BI_CIRCUITO(CIRCUITO_ID),
INCIDENTE_SECTOR INT NOT NULL FOREIGN KEY REFERENCES LOCRO.BI_SECTOR(SECTOR_ID),
INCIDENTE_TIPO INT NOT NULL FOREIGN KEY REFERENCES LOCRO.BI_TIPO_INCIDENTE(TIPO_INCIDENTE_ID),
INCIDENTE_TIPO_DETALLE VARCHAR(255),
INCIDENTE_FECHA DATE,
PRIMARY KEY(INCIDENTE_ID, INCIDENTE_AUTO)
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'BI_INCIDENTES_ESCUDERIA_CIRCUITO')
CREATE TABLE LOCRO.BI_INCIDENTES_ESCUDERIA_CIRCUITO(
CIRCUITO_ID INT NOT NULL,
ESCUDERIA_ID INT NOT NULL,
INCIDENTE_ID INT NOT NULL,
TIPO_INCIDENTE_ID INT NOT NULL,
TIPO_SECTOR_ID INT NOT NULL,
CIRCUITO_NOMBRE VARCHAR(255),
ESCUDERIA_NOMBRE VARCHAR(255),
TIPO_INCIDENTE_DESCRIPCION VARCHAR(255),
TIPO_SECTOR_DESCRIPCION VARCHAR(255),
ANIO INT NOT NULL,
PRIMARY KEY(CIRCUITO_ID, ESCUDERIA_ID, TIPO_SECTOR_ID, INCIDENTE_ID)
);

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_BI_TIEMPO')
DROP PROCEDURE MIGRAR_BI_TIEMPO
GO
CREATE PROCEDURE MIGRAR_BI_TIEMPO
AS
BEGIN
	PRINT('MIGRANDO TIEMPOS...')
	INSERT INTO LOCRO.BI_TIEMPO
	SELECT DISTINCT YEAR(CARRERA_FECHA), CEILING(CAST(MONTH(CARRERA_FECHA) AS decimal(12,2)) / 4)
	FROM LOCRO.CARRERA
	PRINT('TIEMPOS MIGRADOS!!')
END
GO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_BI_ESCUDERIA')
DROP PROCEDURE MIGRAR_BI_ESCUDERIA
GO
CREATE PROCEDURE MIGRAR_BI_ESCUDERIA
AS
BEGIN
	PRINT('MIGRANDO ESCUDERIAS...')
	INSERT INTO LOCRO.BI_ESCUDERIA
	SELECT ESCUDERIA_ID, ESCUDERIA_NOMBRE
	FROM LOCRO.ESCUDERIA
	PRINT('ESCUDERIAS MIGRADAS!!')

END
GO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_BI_CIRCUITO')
DROP PROCEDURE MIGRAR_BI_CIRCUITO
GO
CREATE PROCEDURE MIGRAR_BI_CIRCUITO
AS
BEGIN
	PRINT('MIGRANDO CIRCUITO...')
	INSERT INTO LOCRO.BI_CIRCUITO
	SELECT CIRCUITO_CODIGO, CIRCUITO_NOMBRE
	FROM LOCRO.CIRCUITO
	PRINT('CIRCUITOS MIGRADOS!!')
END
GO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_BI_CARRERA')
DROP PROCEDURE MIGRAR_BI_CARRERA
GO
CREATE PROCEDURE MIGRAR_BI_CARRERA
AS
BEGIN
	PRINT('MIGRANDO CARRERA...')
	INSERT INTO LOCRO.BI_CARRERA
	SELECT CARRERA_CODIGO, CARRERA_CIRCUITO, CARRERA_FECHA
	FROM LOCRO.CARRERA
	PRINT('CARRERAS MIGRADAS!!')
END
GO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_BI_AUTO')
DROP PROCEDURE MIGRAR_BI_AUTO
GO
CREATE PROCEDURE MIGRAR_BI_AUTO
AS
BEGIN
	PRINT('MIGRANDO AUTOS...')
	INSERT INTO LOCRO.BI_AUTO
	SELECT AUTO_ID, AUTO_ESCUDERIA
	FROM LOCRO.AUTO
	PRINT('AUTOS MIGRADOS!!')
END
GO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_BI_PARADA_BOX')
DROP PROCEDURE MIGRAR_BI_PARADA_BOX
GO
CREATE PROCEDURE MIGRAR_BI_PARADA_BOX
AS
BEGIN
	PRINT('MIGRANDO PARADAS...')
	INSERT INTO LOCRO.BI_PARADA_BOX
	SELECT PARADA_ID, PARADA_AUTO, PARADA_CARRERA, PARADA_TIEMPO
	FROM LOCRO.PARADA_BOX
	PRINT('PARADAS MIGRADAS!!')
END
GO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_PARADAS_ESCUDERIAS_CIRCUITO')
DROP PROCEDURE MIGRAR_PARADAS_ESCUDERIAS_CIRCUITO
GO
CREATE PROCEDURE MIGRAR_PARADAS_ESCUDERIAS_CIRCUITO
AS
BEGIN
	PRINT('MIGRANDO HECHOS BOX...')
	INSERT INTO LOCRO.BI_PARADAS_ESCUDERIAS_CIRCUITO
	SELECT CARRERA_CIRCUITO,
	AUTO_ESCUDERIA,
	PARADA_ID,
	TIEMPO_ANIO,
	TIEMPO_CUATRIMESTRE,
	PARADA_TIEMPO,
	e.ESCUDERIA_NOMBRE,
	c.CIRCUITO_NOMBRE
	FROM LOCRO.BI_PARADA_BOX
	JOIN LOCRO.BI_CARRERA ON PARADA_CARRERA = CARRERA_ID
	JOIN LOCRO.BI_CIRCUITO c ON CARRERA_CIRCUITO = c.CIRCUITO_ID
	JOIN LOCRO.BI_AUTO ON PARADA_AUTO = AUTO_ID
	JOIN LOCRO.BI_ESCUDERIA e ON e.ESCUDERIA_ID = AUTO_ESCUDERIA
	JOIN LOCRO.BI_TIEMPO
		ON YEAR(CARRERA_FECHA) = TIEMPO_ANIO AND CEILING(CAST(MONTH(CARRERA_FECHA) AS decimal(3,1))/ 4) = TIEMPO_CUATRIMESTRE
	PRINT('HECHOS BOX MIGRADOS!!')
END
GO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_TIPO_SECTOR')
DROP PROCEDURE MIGRAR_TIPO_SECTOR
GO
CREATE PROCEDURE MIGRAR_TIPO_SECTOR
AS
BEGIN
	PRINT('MIGRANDO TIPOS DE SECTORES...')
	INSERT INTO LOCRO.BI_TIPO_SECTOR
	SELECT TIPO_SECTOR_NUMERO, TIPO_SECTOR_DETALLE
	FROM LOCRO.TIPO_SECTOR
	PRINT('TIPOS DE SECTORES MIGRADOS!!')
END
GO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_SECTOR')
DROP PROCEDURE MIGRAR_SECTOR
GO
CREATE PROCEDURE MIGRAR_SECTOR
AS
BEGIN
	PRINT('MIGRANDO SECTORES...')
	INSERT INTO LOCRO.BI_SECTOR
	SELECT SECTOR_CODIGO, SECTOR_TIPO
	FROM LOCRO.SECTOR
	PRINT('SECTORES MIGRADOS!!')
END
GO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_TIPO_INCIDENTE')
DROP PROCEDURE MIGRAR_TIPO_INCIDENTE
GO
CREATE PROCEDURE MIGRAR_TIPO_INCIDENTE
AS
BEGIN
	PRINT('MIGRANDO TIPOS DE INCIDENTES...')
	INSERT INTO LOCRO.BI_TIPO_INCIDENTE
	SELECT *
	FROM LOCRO.TIPO_INCIDENTE
	PRINT('TIPOS DE INCIDENTES MIGRADOS!!')
END
GO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_INCIDENTE_CIRCUITO')
DROP PROCEDURE MIGRAR_INCIDENTE_CIRCUITO
GO
CREATE PROCEDURE MIGRAR_INCIDENTE_CIRCUITO
AS
BEGIN
	PRINT('MIGRANDO INCIDENTES X CIRCUITO...')
	INSERT INTO LOCRO.BI_INCIDENTE_CIRCUITO
	SELECT
	i.INCIDENTE_ID,
	ia.AUTO_ID,
	c.CARRERA_CIRCUITO,
	i.INCIDENTE_SECTOR,
	TIPO_INCIDENTE_ID,
	TIPO_INCIDENTE_DETALLE,
	c.CARRERA_FECHA
	FROM LOCRO.INCIDENTE i
	JOIN LOCRO.BI_CARRERA c ON i.INCIDENTE_CARRERA = c.CARRERA_ID
	JOIN LOCRO.INCIDENTE_AUTO ia ON i.INCIDENTE_ID = ia.INCIDENTE_ID
	JOIN LOCRO.BI_TIPO_INCIDENTE ON TIPO_INCIDENTE_ID = i.INCIDENTE_TIPO
	PRINT('INCIDENTES X CIRCUITO MIGRADOS!!')
END
GO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_INCIDENTE_ESCUDERIA_CIRCUITO')
DROP PROCEDURE MIGRAR_INCIDENTE_ESCUDERIA_CIRCUITO
GO
CREATE PROCEDURE MIGRAR_INCIDENTE_ESCUDERIA_CIRCUITO
AS
BEGIN
	PRINT('MIGRANDO INCIDENTES X ESCUDERIA X CIRCUITO...')
	INSERT INTO LOCRO.BI_INCIDENTES_ESCUDERIA_CIRCUITO
	SELECT
	INCIDENTE_CIRCUITO,
	AUTO_ESCUDERIA,
	INCIDENTE_ID,
	INCIDENTE_TIPO,
	TIPO_SECTOR_ID,
	CIRCUITO_NOMBRE,
	ESCUDERIA_NOMBRE,
	INCIDENTE_TIPO_DETALLE,
	TIPO_SECTOR_DETALLE,
	YEAR(INCIDENTE_FECHA)
	FROM LOCRO.BI_INCIDENTE_CIRCUITO i
	JOIN LOCRO.BI_AUTO ON AUTO_ID = INCIDENTE_AUTO
	JOIN LOCRO.BI_ESCUDERIA ON ESCUDERIA_ID = AUTO_ESCUDERIA
	JOIN LOCRO.BI_SECTOR ON SECTOR_ID = INCIDENTE_SECTOR
	JOIN LOCRO.BI_TIPO_SECTOR ON SECTOR_TIPO = TIPO_SECTOR_ID
	JOIN LOCRO.BI_CIRCUITO c ON i.INCIDENTE_CIRCUITO = c.CIRCUITO_ID
	PRINT('INCIDENTES X ESCUDERIA X CIRCUITO MIGRADOS!!')
END
GO

IF EXISTS(SELECT [name] FROM sys.views WHERE [name] = 'CIRCUITOS_MAS_TIEMPO_CONSUMIDO')
DROP VIEW CIRCUITOS_MAS_TIEMPO_CONSUMIDO
GO
CREATE VIEW CIRCUITOS_MAS_TIEMPO_CONSUMIDO
AS
	SELECT TOP 3
	CIRCUITO_ID AS 'CODIGO',
	CIRCUITO_NOMBRE AS 'NOMBRE',
	ISNULL(SUM(PARADA_TIEMPO), 0) AS 'TIEMPO TOTAL'
	FROM LOCRO.BI_PARADAS_ESCUDERIAS_CIRCUITO
	GROUP BY CIRCUITO_ID, CIRCUITO_NOMBRE
	ORDER BY 3 DESC
GO

IF EXISTS(SELECT [name] FROM sys.views WHERE [name] = 'CANTIDAD_PARADAS')
DROP VIEW CANTIDAD_PARADAS
GO
CREATE VIEW CANTIDAD_PARADAS
AS
	SELECT
	CIRCUITO_ID AS 'COD.CIRCUITO',
	CIRCUITO_NOMBRE AS 'NOMBRE.CIRCUITO',
	ESCUDERIA_ID AS 'COD.ESCUDERIA',
	ESCUDERIA_NOMBRE AS 'NOMBRE.ESCUDERIA',
	ANIO AS 'ANIO',
	COUNT(*) AS 'CANT.PARADAS'
	FROM LOCRO.BI_PARADAS_ESCUDERIAS_CIRCUITO
	GROUP BY CIRCUITO_ID, CIRCUITO_NOMBRE, ESCUDERIA_ID, ESCUDERIA_NOMBRE, ANIO
GO

IF EXISTS(SELECT [name] FROM sys.views WHERE [name] = 'PROMEDIO_POR_CUATRIMESTRE')
DROP VIEW PROMEDIO_POR_CUATRIMESTRE
GO
CREATE VIEW PROMEDIO_POR_CUATRIMESTRE
AS
	SELECT
	ESCUDERIA_ID AS 'COD.ESCUDERIA',
	ESCUDERIA_NOMBRE AS 'NOMBRE.ESCUDERIA',
	ANIO AS 'ANIO',
	CUATRIMESTRE AS 'CUATRIMESTRE',
	AVG(PARADA_TIEMPO) AS 'PROMEDIO'
	FROM LOCRO.BI_PARADAS_ESCUDERIAS_CIRCUITO
	GROUP BY ESCUDERIA_ID, ESCUDERIA_NOMBRE, ANIO, CUATRIMESTRE
GO

EXEC dbo.MIGRAR_BI_TIEMPO
EXEC dbo.MIGRAR_BI_ESCUDERIA
EXEC dbo.MIGRAR_BI_CIRCUITO
EXEC dbo.MIGRAR_BI_CARRERA
EXEC dbo.MIGRAR_BI_AUTO
EXEC dbo.MIGRAR_BI_PARADA_BOX
EXEC dbo.MIGRAR_PARADAS_ESCUDERIAS_CIRCUITO
EXEC dbo.MIGRAR_TIPO_SECTOR
EXEC dbo.MIGRAR_SECTOR
EXEC dbo.MIGRAR_TIPO_INCIDENTE
EXEC dbo.MIGRAR_INCIDENTE_CIRCUITO
EXEC dbo.MIGRAR_INCIDENTE_ESCUDERIA_CIRCUITO

/*--------------- SELECTS -------------------

SELECT * FROM LOCRO.BI_TIEMPO
SELECT * FROM LOCRO.BI_ESCUDERIA
SELECT * FROM LOCRO.BI_CIRCUITO
SELECT * FROM LOCRO.BI_CARRERA
SELECT * FROM LOCRO.BI_AUTO
SELECT * FROM LOCRO.BI_PARADA_BOX
SELECT * FROM LOCRO.BI_PARADAS_ESCUDERIAS_CIRCUITO
SELECT * FROM LOCRO.BI_TIPO_SECTOR
SELECT * FROM LOCRO.BI_SECTOR
SELECT * FROM LOCRO.BI_TIPO_INCIDENTE
SELECT * FROM LOCRO.BI_INCIDENTE_CIRCUITO
SELECT * FROM LOCRO.BI_INCIDENTES_ESCUDERIA_CIRCUITO

----------------- VIEWS -----------------

SELECT * FROM CIRCUITOS_MAS_TIEMPO_CONSUMIDO
SELECT * FROM CANTIDAD_PARADAS
SELECT * FROM PROMEDIO_POR_CUATRIMESTRE

---------------- DROPEAR TABLAS ------------------

DROP TABLE LOCRO.BI_CARRERA
DROP TABLE LOCRO.BI_AUTO
DROP TABLE LOCRO.BI_PARADA_BOX
DROP TABLE LOCRO.BI_ESCUDERIA
DROP TABLE LOCRO.BI_CIRCUITO
DROP TABLE LOCRO.BI_TIEMPO
DROP table LOCRO.BI_PARADAS_ESCUDERIAS_CIRCUITO
DROP TABLE LOCRO.BI_TIPO_SECTOR
DROP TABLE LOCRO.BI_SECTOR
DROP TABLE LOCRO.BI_TIPO_INCIDENTE
DROP TABLE LOCRO.BI_INCIDENTE_CIRCUITO
DROP TABLE LOCRO.BI_INCIDENTES_ESCUDERIA_CIRCUITO

*/
