USE GD1C2022
GO

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'BI_TIEMPO')
CREATE TABLE LOCRO.BI_TIEMPO(
TIEMPO_ID INT IDENTITY PRIMARY KEY,
TIEMPO_ANIO INT not null,
TIEMPO_CUATRIMESTRE INT null,
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'BI_ESCUDERIA')
CREATE TABLE LOCRO.BI_ESCUDERIA(
ESCUDERIA_ID INT PRIMARY KEY,
ESCUDERIA_NOMBRE VARCHAR(255)
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'BI_CIRCUITO')
CREATE TABLE LOCRO.BI_CIRCUITO(
CIRCUITO_ID INT PRIMARY KEY,
CIRCUITO_NOMBRE VARCHAR(255)
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'BI_CARRERA')
CREATE TABLE LOCRO.BI_CARRERA(
CARRERA_ID INT PRIMARY KEY,
CARRERA_CIRCUITO INT FOREIGN KEY REFERENCES LOCRO.BI_CIRCUITO(CIRCUITO_ID),
CARRERA_TIEMPO INT FOREIGN KEY REFERENCES LOCRO.BI_TIEMPO(TIEMPO_ID)
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'BI_AUTO')
CREATE TABLE LOCRO.BI_AUTO(
AUTO_ID INT PRIMARY KEY,
AUTO_ESCUDERIA INT FOREIGN KEY REFERENCES LOCRO.BI_ESCUDERIA(ESCUDERIA_ID)
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'BI_PARADA_BOX')
CREATE TABLE LOCRO.BI_PARADA_BOX(
PARADA_ID INT PRIMARY KEY,
PARADA_AUTO INT FOREIGN KEY REFERENCES LOCRO.BI_AUTO(AUTO_ID),
PARADA_CARRERA INT FOREIGN KEY REFERENCES LOCRO.BI_CARRERA(CARRERA_ID),
PARADA_TIEMPO decimal(18,2)
);

IF NOT EXISTS(SELECT [name] FROM sys.tables WHERE [name] = 'BI_HECHOS_BOX')
CREATE TABLE LOCRO.BI_HECHOS_BOX(
CIRCUITO_ID INT NOT NULL,
ESCUDERIA_ID INT NOT NULL,
TIEMPO_ID INT NOT NULL,
PARADA_ID INT NOT NULL,
PRIMARY KEY(CIRCUITO_ID, ESCUDERIA_ID, TIEMPO_ID, PARADA_ID)
);

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_BI_TIEMPO')
DROP PROCEDURE MIGRAR_BI_TIEMPO
GO
CREATE PROCEDURE MIGRAR_BI_TIEMPO
AS
BEGIN
	PRINT('MIGRANDO TIEMPOS...')
	INSERT INTO LOCRO.BI_TIEMPO
	SELECT DISTINCT YEAR(CARRERA_FECHA), CEILING(CAST(MONTH(CARRERA_FECHA) AS decimal(12,2)) / 4)
	FROM LOCRO.CARRERA
	PRINT('TIEMPOS MIGRADOS!!')
END
GO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_BI_ESCUDERIA')
DROP PROCEDURE MIGRAR_BI_ESCUDERIA
GO
CREATE PROCEDURE MIGRAR_BI_ESCUDERIA
AS
BEGIN
	PRINT('MIGRANDO ESCUDERIAS...')
	INSERT INTO LOCRO.BI_ESCUDERIA
	SELECT ESCUDERIA_ID, ESCUDERIA_NOMBRE
	FROM LOCRO.ESCUDERIA
	PRINT('ESCUDERIAS MIGRADAS!!')

END
GO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_BI_CIRCUITO')
DROP PROCEDURE MIGRAR_BI_CIRCUITO
GO
CREATE PROCEDURE MIGRAR_BI_CIRCUITO
AS
BEGIN
	PRINT('MIGRANDO CIRCUITO...')
	INSERT INTO LOCRO.BI_CIRCUITO
	SELECT CIRCUITO_CODIGO, CIRCUITO_NOMBRE
	FROM LOCRO.CIRCUITO
	PRINT('CIRCUITOS MIGRADOS!!')
END
GO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_BI_CARRERA')
DROP PROCEDURE MIGRAR_BI_CARRERA
GO
CREATE PROCEDURE MIGRAR_BI_CARRERA
AS
BEGIN
	PRINT('MIGRANDO CARRERA...')
	INSERT INTO LOCRO.BI_CARRERA
	SELECT CARRERA_CODIGO, CARRERA_CIRCUITO, TIEMPO_ID
	FROM LOCRO.CARRERA
	JOIN LOCRO.BI_TIEMPO
		ON YEAR(CARRERA_FECHA) = TIEMPO_ANIO AND CEILING(CAST(MONTH(CARRERA_FECHA) AS decimal(3,1)) / 4) = TIEMPO_CUATRIMESTRE
	PRINT('CARRERAS MIGRADAS!!')
END
GO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_BI_AUTO')
DROP PROCEDURE MIGRAR_BI_AUTO
GO
CREATE PROCEDURE MIGRAR_BI_AUTO
AS
BEGIN
	PRINT('MIGRANDO AUTOS...')
	INSERT INTO LOCRO.BI_AUTO
	SELECT AUTO_ID, AUTO_ESCUDERIA
	FROM LOCRO.AUTO
	PRINT('AUTOS MIGRADOS!!')
END
GO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_BI_PARADA_BOX')
DROP PROCEDURE MIGRAR_BI_PARADA_BOX
GO
CREATE PROCEDURE MIGRAR_BI_PARADA_BOX
AS
BEGIN
	PRINT('MIGRANDO PARADAS...')
	INSERT INTO LOCRO.BI_PARADA_BOX
	SELECT PARADA_ID, PARADA_AUTO, PARADA_CARRERA, PARADA_TIEMPO
	FROM LOCRO.PARADA_BOX
	PRINT('PARADAS MIGRADAS!!')
END
GO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_HECHOS_BOX')
DROP PROCEDURE MIGRAR_HECHOS_BOX
GO
CREATE PROCEDURE MIGRAR_HECHOS_BOX
AS
BEGIN
	PRINT('MIGRANDO HECHOS BOX...')
	INSERT INTO LOCRO.BI_HECHOS_BOX
	SELECT CARRERA_CIRCUITO, AUTO_ESCUDERIA, TIEMPO_ID, PARADA_ID
	FROM LOCRO.BI_PARADA_BOX
	JOIN LOCRO.BI_CARRERA ON PARADA_CARRERA = CARRERA_ID
	JOIN LOCRO.BI_AUTO ON PARADA_AUTO = AUTO_ID
	JOIN LOCRO.BI_TIEMPO ON CARRERA_TIEMPO = TIEMPO_ID
	PRINT('HECHOS BOX MIGRADOS!!')
END
GO

IF EXISTS(SELECT [name] FROM sys.views WHERE [name] = 'CIRCUITOS_MAS_TIEMPO_CONSUMIDO')
DROP VIEW CIRCUITOS_MAS_TIEMPO_CONSUMIDO
GO
CREATE VIEW CIRCUITOS_MAS_TIEMPO_CONSUMIDO
AS
	SELECT TOP 3
	h.CIRCUITO_ID AS 'CODIGO',
	(SELECT CIRCUITO_NOMBRE FROM LOCRO.BI_CIRCUITO c WHERE h.CIRCUITO_ID = c.CIRCUITO_ID) AS 'NOMBRE',
	ISNULL(SUM(p.PARADA_TIEMPO), 0) AS 'TIEMPO TOTAL'
	FROM LOCRO.BI_HECHOS_BOX h
	JOIN LOCRO.BI_PARADA_BOX p ON h.PARADA_ID = p.PARADA_ID
	GROUP BY h.CIRCUITO_ID
	ORDER BY 3 DESC
GO

IF EXISTS(SELECT [name] FROM sys.views WHERE [name] = 'CANTIDAD_PARADAS')
DROP VIEW CANTIDAD_PARADAS
GO
CREATE VIEW CANTIDAD_PARADAS
AS
	SELECT
	h.CIRCUITO_ID AS 'COD.CIRCUITO',
	(SELECT c.CIRCUITO_NOMBRE FROM LOCRO.BI_CIRCUITO c WHERE c.CIRCUITO_ID = h.CIRCUITO_ID) AS 'NOMBRE.CIRCUITO',
	h.ESCUDERIA_ID AS 'COD.ESCUDERIA',
	(SELECT e.ESCUDERIA_NOMBRE FROM LOCRO.BI_ESCUDERIA e WHERE e.ESCUDERIA_ID = h.ESCUDERIA_ID) AS 'NOMBRE.ESCUDERIA',
	t.TIEMPO_ANIO AS 'ANIO',
	COUNT(*) AS 'CANT.PARADAS'
	FROM LOCRO.BI_HECHOS_BOX h
	JOIN LOCRO.BI_TIEMPO t
		ON h.TIEMPO_ID = t.TIEMPO_ID
	GROUP BY h.CIRCUITO_ID, h.ESCUDERIA_ID, t.TIEMPO_ANIO
GO

IF EXISTS(SELECT [name] FROM sys.views WHERE [name] = 'PROMEDIO_POR_CUATRIMESTRE')
DROP VIEW PROMEDIO_POR_CUATRIMESTRE
GO
CREATE VIEW PROMEDIO_POR_CUATRIMESTRE
AS
	SELECT
	h.ESCUDERIA_ID AS 'COD.ESCUDERIA',
	(SELECT e.ESCUDERIA_NOMBRE FROM LOCRO.BI_ESCUDERIA e WHERE e.ESCUDERIA_ID = h.ESCUDERIA_ID) AS 'NOMBRE.ESCUDERIA',
	t.TIEMPO_ANIO AS 'ANIO',
	t.TIEMPO_CUATRIMESTRE AS 'CUATRIMESTRE',
	AVG(p.PARADA_TIEMPO) AS 'PROMEDIO'
	FROM LOCRO.BI_HECHOS_BOX h
	JOIN LOCRO.BI_TIEMPO t ON h.TIEMPO_ID = t.TIEMPO_ID
	JOIN LOCRO.BI_PARADA_BOX p ON p.PARADA_ID = h.PARADA_ID
	GROUP BY h.ESCUDERIA_ID, t.TIEMPO_ANIO, t.TIEMPO_CUATRIMESTRE
GO

EXEC dbo.MIGRAR_BI_TIEMPO
EXEC dbo.MIGRAR_BI_ESCUDERIA
EXEC dbo.MIGRAR_BI_CIRCUITO
EXEC dbo.MIGRAR_BI_CARRERA
EXEC dbo.MIGRAR_BI_AUTO
EXEC dbo.MIGRAR_BI_PARADA_BOX
EXEC MIGRAR_HECHOS_BOX

/*--------------- SELECTS -------------------

SELECT * FROM LOCRO.BI_TIEMPO
SELECT * FROM LOCRO.BI_ESCUDERIA
SELECT * FROM LOCRO.BI_CIRCUITO
SELECT * FROM LOCRO.BI_CARRERA
SELECT * FROM LOCRO.BI_AUTO
SELECT * FROM LOCRO.BI_PARADA_BOX
SELECT * FROM LOCRO.BI_HECHOS_BOX

----------------- VIEWS -----------------

SELECT * FROM CIRCUITOS_MAS_TIEMPO_CONSUMIDO
SELECT * FROM CANTIDAD_PARADAS
SELECT * FROM PROMEDIO_POR_CUATRIMESTRE

---------------- DROPEAR TABLAS ------------------

DROP TABLE LOCRO.BI_CARRERA
DROP TABLE LOCRO.BI_AUTO
DROP TABLE LOCRO.BI_PARADA_BOX
DROP TABLE LOCRO.BI_ESCUDERIA
DROP TABLE LOCRO.BI_CIRCUITO
DROP TABLE LOCRO.BI_TIEMPO
DROP table LOCRO.BI_HECHOS_BOX

*/
